---
title: Agent Blue Staffing
description: The Cross Orlando is a congregation of people living under the reign
  of God. We gather together regularly, we're working in all sectors of our city and
  are always looking for ways to better care for each other.
url: https://agentbluestaffing.com
markdown: kramdown
defaults:
- scope:
    path: ''
  values:
    layout: default
